
#---standard pioneer footprint---
#---(in meters)---
#footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]
#footprint: [[0.171,-0.128], [0.171,0.128], [-0.171,0.128], [-0.171,-0.128]]
robot_radius: 0.08

transform_tolerance: 0.2

obstacle_layer:
 enabled: true
 obstacle_range: 2.0
 raytrace_range: 2.0
 inflation_radius: 0.11
 track_unknown_space: true
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {
    sensor_frame: laser_frame,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true,
    inf_is_valid: true
  }


inflation_layer:
  enabled:              true
  cost_scaling_factor:  31 #5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.22  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
