global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3
  publish_frequency: 1.6

  inflation_radius: 0.4

  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}




